### ISSUE TITLE
Only layers of same output shape can be merged using sum mode.

### ISSUE THREAD

**Issue by aman-tiwari** [raghakot/keras-resnet#17]
Using input shape (3, 300, 300), with 5 labels:
`model = ResNetBuilder.build_resnet_50((3, 300, 300), 5)`

I get the error: 
`Exception: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 1, 75, 64), (None, 1, 75, 256)]     
`

What input sizes can be used?

**Comment by mel-2445** [comment]
@aman-tiwari , changing
```
stride_width = input._keras_shape[2] // residual._keras_shape[2]
stride_height = input._keras_shape[3] // residual._keras_shape[3]
```
on lines 45, 46 to 
```
stride_width = (input._keras_shape[2] - 1) // (residual._keras_shape[2] - 1)
stride_height = (input._keras_shape[3] - 1) // (residual._keras_shape[3] - 1)
```
seems to work, as calculating the stride should follow `W = (W1-F+2P) / S + 1` where `W` is the desired width, `W1` the original width, `F` is 1, and `P` is 0.

**Comment by aman-tiwari** [comment]
I still get the same error. I'm using the TF backend, are you using the Theano one?

**Comment by aman-tiwari** [comment]
It works if I use that fix and the `resnet.py` from this pull request: https://github.com/raghakot/keras-resnet/pull/14

**Comment by raghakot** [comment]
I merged that PR. closing.

**Comment by mingwugmail** [comment]
change size to (3, 200, 200) will cause the same error in 
 ./tests/test_resnet.py 
           model = ResnetBuilder.build_resnet_18((3, 200, 200), 100)

E               ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 25, 25, 256), (None, 13, 13, 256)]
