### ISSUE TITLE
I had this error

### ISSUE THREAD

**Issue by a-bacilio** [raghakot/keras-resnet#30]
Hi Mr raghakot
Im very thankful for your work in resnet 

the issue was that
I had this error while trying this
#########################################3
Error: 
 input = block_function(nb_filter,init_subsample,(is_first_layer and (i == 0)))(input)

TypeError: 'str' object is not callable
------------------------------------------------------------------------------------------------
#########################################3

while trying to run this:
------------------------------------------------------------------------------------------------
model=ResnetBuilder.build((3,100,100), 1, 'bottleneck',[1])
model.summary()
------------------------------------------------------------------------------------------------
#########################################3
So then I went to resnet.py and changed this
-----------------------------------
def _residual_block(block_function, nb_filter, repetitions, is_first_layer=False):

    """Builds a residual block with repeating bottleneck blocks.

    """

    def f(input):

        for i in range(repetitions):

            init_subsample = (1, 1)

            if i == 0 and not is_first_layer:

                init_subsample = (2, 2)

            input = block_function(

                    nb_filter=nb_filter,

                    init_subsample=init_subsample,

                    is_first_block_of_first_layer=(is_first_layer and i == 0)

                )(input)

        return input

    return f

----------------------------------------------------------
to this : 
----------------------------------------------------------
def _residual_block(block_function, nb_filter, repetitions, is_first_layer=False):
    """Builds a residual block with repeating bottleneck blocks.
    """
    def f(input):
        for i in range(repetitions):
            init_subsample = (1, 1)
            if i == 0 and not is_first_layer:
                init_subsample = (2, 2)
            if block_function=='basic_block':
                input = basic_block(nb_filter,init_subsample,(is_first_layer and (i == 0)))(input)
            elif block_function=='bottleneck':
                input = bottleneck(nb_filter,init_subsample,(is_first_layer and (i == 0)))(input)
            else:
                print('llamada a funcion extraña')
        return input

    return f
----------------------------------------------------
I would like to know if it could still working correctly after doing that. 
------------------------------------------------------------
Thank you very much for your help

**Comment by raghakot** [comment]
you need to pass `resnet.bottleneck`. The `block_fn` param is not a string.

**Comment by raghakot** [comment]
I can see how this might be confusing. Will update the code to accept strings

**Comment by raghakot** [comment]
I pushed a commit that handles str function names. Your sample should work now.

**Comment by a-bacilio** [comment]
Thank you raghakot ,  :D
