### ISSUE TITLE
Only layers of same output shape can be merged using sum mode.

### ISSUE THREAD

**Issue by mingwugmail** [raghakot/keras-resnet#34]
for shape (3, 200, 200)

basically reopen issue #17 

https://github.com/raghakot/keras-resnet/issues/17?_pjax=%23js-repo-pjax-container

**Comment by mingwugmail** [comment]
change tests/test_resnet.py
        model = ResnetBuilder.build_resnet_18((3, 300, 300), 100)

still fails.

**Comment by HarryPratt** [comment]
I also get this issue when using other inputs i.e ((3,512,512),2). I believe it is again an issue with the subsample sizes [https://github.com/raghakot/keras-resnet/blob/master/resnet.py#L81](url)
