### ISSUE TITLE
Adapt Keras 2 API

### ISSUE THREAD

**Issue by JihongJu** [raghakot/keras-resnet#38]
Keras has just released [Keras 2 which introduced significant API changes](https://blog.keras.io/introducing-keras-2.html) and the old API will not be supported anymore from August 2017. The main difference that matters is the change of arguments names.

I am kind of annoyed by the warnings pop-up every time before training so I just changed those names myself and I am willing to send a PR for those changes.

See PR #39

**Comment by raghakot** [comment]
Thanks.

**Comment by JihongJu** [comment]
Thanks.
