### ISSUE TITLE
the pool mode issue in the last pool layer

### ISSUE THREAD

**Issue by GeorgeXia1828** [raghakot/keras-resnet#9]
I noticed that the last layer pool in your network:
`pool2 = AveragePooling2D(pool_size=(7, 7), strides=(1, 1), border_mode="same")(block4)`
and I check then the output size will be still 7*7 for the reason mode = "same", However, the output size in the paper is told to be 1, should here to modify the mode = "valid"?

**Comment by junfenglx** [comment]
Yes, you are right.
See the implementation of Keras example:
https://github.com/fchollet/keras/blob/master/examples/resnet_50.py#L195

Also the doc says that `border_mode="same"` only works for TF.

And the visualization of the input_shape of the last dense layer is not correct.
It should be (None, 2048), not (None, `100352 = 2048 * 49`)

**Comment by kaonashi-tyc** [comment]
Should we use VALID in the averaging pooling layer? Is seems that this is the default behavior in the CNTK implementation:

https://github.com/Microsoft/CNTK/blob/9d6345b2fa794c38b4f02f71631ea71401b97362/Tests/EndToEndTests/Examples/Image/Miscellaneous/CIFAR-10/03_ResNet/baseline.linux.gpu.txt#L773

**Comment by raghakot** [comment]
Thanks for pointing that out. fixed
